name: Android CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 1.8
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: 8
    - name: Build with Gradle
      run: ./gradlew --stacktrace
    - name: Test with Gradle
      run: ./gradlew :core:test --stacktrace
    - name: Run Examples
      run: ./gradlew :examples:build --stacktrace
    - name: Build Project
      run: ./gradlew build
